import Link from "next/link";

type VerifyPageProps = {
  searchParams?: Promise<{ id?: string | string[] }>;
};

const certificateIdPattern = /^BHRT-CYB-[A-Z0-9]{4}-[A-Z0-9]{4}-\d{8}$/;

export default async function VerifyPage({ searchParams }: VerifyPageProps) {
  const params = searchParams ? await searchParams : {};
  const rawId = Array.isArray(params.id) ? params.id[0] : params.id;
  const certificateId = rawId?.trim() ?? "";
  const isValidFormat = certificateIdPattern.test(certificateId);

  return (
    <div className="min-h-screen bg-[#050B14] text-[#ECF2FA]">
      <div className="h-[6px] w-full bg-[linear-gradient(90deg,#FF9933_0%,#FF9933_33%,#fff_33%,#fff_66%,#128807_66%)]" aria-hidden="true" />
      <header className="border-b border-white/10 bg-[#0A1424] px-5 py-4 md:px-8">
        <div className="mx-auto flex w-full max-w-3xl items-center justify-between gap-4">
          <Link href="/" className="text-xl font-extrabold tracking-wide text-[#FF9933]">Bharat App</Link>
          <span className="text-sm text-[#C8D5EA]">Certificate Verification</span>
        </div>
      </header>
      <main className="mx-auto flex min-h-[calc(100vh-110px)] w-full max-w-3xl items-center px-5 py-10 md:px-8">
        <section className="w-full rounded-2xl border border-white/10 bg-[#0A1424] p-6 shadow-xl md:p-10">
          <p className="text-sm font-semibold uppercase tracking-wider text-[#FF9933]">Cyber Awareness Academy</p>
          <h1 className="mt-2 text-3xl font-bold">Certificate verification</h1>
          {certificateId ? (
            <>
              <p className="mt-6 text-sm text-[#C8D5EA]">Certificate ID</p>
              <p className="mt-2 break-all rounded-lg border border-[#D4AF37]/50 bg-[#050B14] px-4 py-3 font-mono text-lg text-[#FFE9a3]">
                {certificateId}
              </p>
              <p className={`mt-5 rounded-lg border p-4 text-sm ${isValidFormat ? "border-[#128807]/60 bg-[#128807]/15 text-[#dcfce7]" : "border-[#d93838]/60 bg-[#d93838]/15 text-[#ffd6d6]"}`}>
                {isValidFormat
                  ? "This certificate ID was generated by Bharat App's Cyber Awareness Academy. Certificate verification database coming soon — for now this confirms the ID format is valid."
                  : "This certificate ID does not match the Bharat App format yet. Please check the scanned URL or certificate text."}
              </p>
            </>
          ) : (
            <p className="mt-6 rounded-lg border border-[#d93838]/60 bg-[#d93838]/15 p-4 text-sm text-[#ffd6d6]">
              No certificate ID was provided. Scan a Bharat App certificate QR code or open a URL with an <code>id</code> query parameter.
            </p>
          )}
          <Link href="/" className="mt-6 inline-flex rounded-full bg-[#FF9933] px-5 py-2 font-semibold text-white hover:bg-[#e58621]">
            Back to Bharat App
          </Link>
        </section>
      </main>
    </div>
  );
}
